apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-helloworld
spec:
  template:
    metadata:
      name: knative-helloworld-v1
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          env:
            - name: TARGET
              value: "From Kubernetes Serverless World!"